### ISSUE TITLE
It is easy to add telemetry/logging for CPU and GPU

### ISSUE THREAD

**Issue by billzorn** [uwsampl/relay-bench#42]
CPU:
```sensors```
then do things with `sed`

GPU:
```
nvidia-smi --format=csv --query-gpu="clocks.gr,clocks.current.memory,utilization.gpu,utilization.memory,pstate,power.draw,power.limit,temperature.gpu,temperature.memory,fan.speed"
```
You could read more about the documentation of `nvidia-smi`, but that query should cover most of the things you would care about logging.

My advice: set up a process that gets some numbers you care about every 5 or 10 seconds, and then logs them. With your infrastructure it should be easy to plot the logs and see if anything funny is going on. The queries themselves shouldn't have too much impact on performance, and I don't think you'll need a granularity finer than about 5 or 10 seconds.

**Comment by slyubomirsky** [comment]
Thanks, Bill, we've gone with this suggestion and implemented a telemetry subsystem
